# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipsNationalCompetitionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_ko', models.CharField(max_length=50)),
                ('name_pt', models.CharField(max_length=50)),
                ('name_th', models.CharField(max_length=50)),
                ('name_id', models.CharField(max_length=50)),
                ('name_vi', models.CharField(max_length=50)),
                ('ut', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '대회이름입력',
                'verbose_name_plural': '대회이름입력',
                'db_table': 'swips_national_competition_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsNationalTeamInfoCompetition',
            fields=[
                ('team', models.AutoField(primary_key=True, serialize=False)),
                ('competition', models.IntegerField()),
                ('no_champions', models.IntegerField()),
                ('appearance', models.IntegerField()),
                ('best_result', models.CharField(max_length=20)),
                ('no_champions_desc', models.CharField(max_length=15)),
                ('appearance_desc', models.CharField(max_length=15)),
                ('best_result_desc', models.CharField(max_length=15)),
                ('last_result_desc', models.CharField(max_length=15)),
                ('valid_until', models.CharField(max_length=20)),
                ('ut', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': '국가별대회정보',
                'verbose_name_plural': '국가별대회정보',
                'db_table': 'swips_national_team_info_competition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsNationalTeamInfoWC',
            fields=[
                ('team', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('fifa_ranking', models.PositiveIntegerField()),
                ('no_champions', models.IntegerField()),
                ('appearance', models.IntegerField()),
                ('best_result', models.CharField(max_length=20)),
                ('last_result', models.CharField(max_length=20)),
                ('no_champions_desc', models.CharField(max_length=150)),
                ('appearance_desc', models.CharField(max_length=150)),
                ('best_result_desc', models.CharField(max_length=150)),
                ('last_result_desc', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': '국가별WC정보',
                'verbose_name_plural': '국가별WC정보',
                'db_table': 'swips_national_team_info_wc',
                'managed': False,
            },
        ),
    ]
