# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipsQna',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='anom id')),
                ('account_id', models.IntegerField(help_text='swips account id')),
                ('user_agent', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=32, null=True)),
                ('feedback', models.TextField(blank=True, help_text='피드백', null=True)),
                ('img_ext', models.CharField(blank=True, max_length=5, null=True)),
                ('img_rot', models.IntegerField(blank=True, null=True)),
                ('img_width', models.IntegerField(blank=True, null=True)),
                ('img_height', models.IntegerField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, help_text='답글', null=True)),
                ('ut', models.DateTimeField(blank=True, help_text='피드백 올라온 시각', null=True)),
                ('answer_ut', models.DateTimeField(blank=True, help_text='답글 단 시각', null=True)),
                ('status', models.CharField(blank=True, help_text='ready : 답글X answered : 답글 O', max_length=9, null=True)),
                ('field_del', models.IntegerField(db_column='_del')),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백',
                'db_table': 'swips_qna',
                'managed': False,
            },
        ),
    ]
