# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipsFeedback',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_agent', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('ut', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백',
                'db_table': 'swips_feedback',
                'managed': False,
            },
        ),
    ]
