# Generated by Django 2.0.4 on 2018-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipsRating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('rating', models.FloatField()),
                ('source', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'swips_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsRatingProperty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mom_id', models.IntegerField(blank=True, null=True)),
                ('mom_goal', models.IntegerField(blank=True, null=True)),
                ('mom_assist', models.IntegerField(blank=True, null=True)),
                ('mom_min', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swips_rating_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsReview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sport', models.IntegerField()),
                ('league', models.IntegerField()),
                ('result', models.TextField(blank=True, null=True)),
                ('ut', models.DateTimeField()),
                ('standing', models.TextField(blank=True, null=True)),
                ('startdate', models.DateTimeField()),
                ('ct', models.DateTimeField()),
                ('pushed', models.IntegerField()),
            ],
            options={
                'db_table': 'swips_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorldPeacePreview',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_info', models.CharField(blank=True, max_length=45, null=True)),
                ('team1', models.IntegerField(blank=True, null=True)),
                ('team2', models.IntegerField(blank=True, null=True)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('team1_rank', models.CharField(blank=True, max_length=45, null=True)),
                ('team2_rank', models.CharField(blank=True, max_length=45, null=True)),
                ('team1_win', models.IntegerField(blank=True, null=True)),
                ('team2_win', models.IntegerField(blank=True, null=True)),
                ('team1_draw', models.IntegerField(blank=True, null=True)),
                ('team2_draw', models.IntegerField(blank=True, null=True)),
                ('team1_defeit', models.IntegerField(blank=True, null=True)),
                ('team2_defeit', models.IntegerField(blank=True, null=True)),
                ('team1_pts', models.IntegerField(blank=True, null=True)),
                ('team2_pts', models.IntegerField(blank=True, null=True)),
                ('team1_result', models.CharField(blank=True, max_length=45, null=True)),
                ('team2_result', models.CharField(blank=True, max_length=45, null=True)),
                ('team1_goals_per_game', models.FloatField(blank=True, null=True)),
                ('team2_goals_per_game', models.FloatField(blank=True, null=True)),
                ('team1_goals_per_game_5', models.FloatField(blank=True, null=True)),
                ('team2_goals_per_game_5', models.FloatField(blank=True, null=True)),
                ('team1_goals_against_per_game', models.FloatField(blank=True, null=True)),
                ('team2_goals_against_per_game', models.FloatField(blank=True, null=True)),
                ('team1_goals_against_per_game_5', models.FloatField(blank=True, null=True)),
                ('team2_goals_against_per_game_5', models.FloatField(blank=True, null=True)),
                ('team1_key_player', models.IntegerField(blank=True, null=True)),
                ('team2_key_player', models.IntegerField(blank=True, null=True)),
                ('team1_key_player_goal', models.IntegerField(blank=True, null=True)),
                ('team2_key_player_goal', models.IntegerField(blank=True, null=True)),
                ('team1_key_player_assist', models.IntegerField(blank=True, null=True)),
                ('team2_key_player_assist', models.IntegerField(blank=True, null=True)),
                ('team1_top_player', models.CharField(blank=True, max_length=45, null=True)),
                ('team2_top_player', models.CharField(blank=True, max_length=45, null=True)),
                ('team1_top_player_stat', models.CharField(blank=True, max_length=45, null=True)),
                ('team2_top_player_stat', models.CharField(blank=True, max_length=45, null=True)),
                ('team1_top_player_stat_per', models.CharField(blank=True, max_length=45, null=True)),
                ('team2_top_player_stat_per', models.CharField(blank=True, max_length=45, null=True)),
                ('team1_injuries', models.CharField(blank=True, max_length=45, null=True)),
                ('team2_injuries', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=9)),
                ('type', models.IntegerField()),
                ('league', models.IntegerField()),
            ],
            options={
                'db_table': 'world_peace_preview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpFixtures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match', models.IntegerField(blank=True, null=True, unique=True)),
                ('tournament', models.IntegerField(blank=True, null=True)),
                ('league', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('team1', models.IntegerField(blank=True, null=True)),
                ('team2', models.IntegerField(blank=True, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('p_type', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=9)),
                ('pushed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_fixtures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpInjuries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('player', models.IntegerField(blank=True, null=True)),
                ('match', models.IntegerField(blank=True, null=True)),
                ('team', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_injuries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpKeyPl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField()),
                ('team', models.IntegerField()),
                ('player', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('rating', models.FloatField()),
                ('played', models.IntegerField()),
                ('n', models.IntegerField()),
            ],
            options={
                'db_table': 'wp_key_pl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpTeamStat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField(blank=True, null=True)),
                ('team', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('defeit', models.IntegerField(blank=True, null=True)),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('prev_rank', models.CharField(blank=True, max_length=32, null=True)),
                ('prev_result', models.CharField(blank=True, max_length=32, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('goals_re', models.FloatField(blank=True, null=True)),
                ('ga_s', models.IntegerField(blank=True, null=True)),
                ('ga_s_re', models.FloatField(blank=True, null=True)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('ratings_re', models.FloatField(blank=True, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_team_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpTopPl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField(blank=True, null=True)),
                ('team', models.IntegerField(blank=True, null=True)),
                ('player', models.IntegerField(blank=True, null=True)),
                ('stat_type', models.CharField(blank=True, max_length=7, null=True)),
                ('stat', models.FloatField(blank=True, null=True)),
                ('avg_stat', models.FloatField(blank=True, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_top_pl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpTransfer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tournament', models.IntegerField(blank=True, null=True)),
                ('team', models.IntegerField(blank=True, null=True)),
                ('player', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.CharField(blank=True, max_length=3, null=True)),
                ('ut', models.CharField(blank=True, max_length=20, null=True)),
                ('del_field', models.IntegerField(db_column='del')),
            ],
            options={
                'db_table': 'wp_transfer',
                'managed': False,
            },
        ),
    ]
