# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preview_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swipsrating',
            options={'managed': False, 'verbose_name': '리뷰 Rating(raw)', 'verbose_name_plural': '리뷰 Rating(raw)'},
        ),
        migrations.AlterModelOptions(
            name='swipsratingproperty',
            options={'managed': False, 'verbose_name': '리뷰 MOM(raw)', 'verbose_name_plural': '리뷰 MOM(raw)'},
        ),
        migrations.AlterModelOptions(
            name='swipsreview',
            options={'managed': False, 'verbose_name': '리뷰(raw)', 'verbose_name_plural': '리뷰(raw)'},
        ),
        migrations.AlterModelOptions(
            name='worldpeacepreview',
            options={'managed': False, 'verbose_name': '웹 프리뷰', 'verbose_name_plural': '웹 프리뷰'},
        ),
        migrations.AlterModelOptions(
            name='wpfixtures',
            options={'managed': False, 'verbose_name': '인앱 프리뷰 Fixtures(raw)', 'verbose_name_plural': '인앱 프리뷰 Fixtures(raw)'},
        ),
        migrations.AlterModelOptions(
            name='wpinjuries',
            options={'managed': False, 'verbose_name': '인앱 프리뷰 부상자명단(raw)', 'verbose_name_plural': '인앱 프리뷰 부상자 명단(raw)'},
        ),
        migrations.AlterModelOptions(
            name='wpkeypl',
            options={'managed': False, 'verbose_name': '인앱 프리뷰 키플레이어(raw)', 'verbose_name_plural': '인앱 프리뷰 키플레이어(raw)'},
        ),
        migrations.AlterModelOptions(
            name='wpteamstat',
            options={'managed': False, 'verbose_name': '인앱 프리뷰 팀 스탯(raw)', 'verbose_name_plural': '인앱 프리뷰 팀 스탯(raw)'},
        ),
        migrations.AlterModelOptions(
            name='wptoppl',
            options={'managed': False, 'verbose_name': '인앱 프리뷰 탑플레이어(raw)', 'verbose_name_plural': '인앱 프리뷰 탑플레이어(raw)'},
        ),
        migrations.AlterModelOptions(
            name='wptransfer',
            options={'managed': False, 'verbose_name': '인앱 프리뷰 이적(raw)', 'verbose_name_plural': '인앱 프리뷰 이적(raw)'},
        ),
    ]
