# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currynews',
            options={'managed': False, 'verbose_name': '뉴스 팔로잉', 'verbose_name_plural': '뉴스 팔로잉'},
        ),
        migrations.AlterModelOptions(
            name='curryvod',
            options={'managed': False, 'verbose_name': 'VOD', 'verbose_name_plural': 'VOD'},
        ),
        migrations.AlterModelOptions(
            name='swipscrawlingsource',
            options={'managed': False, 'verbose_name': '크롤링 소스 리스트', 'verbose_name_plural': '크롤링 소스 리스트'},
        ),
        migrations.AlterModelOptions(
            name='swipsnews',
            options={'managed': False, 'verbose_name': '뉴스 리스트', 'verbose_name_plural': '뉴스 리스트'},
        ),
        migrations.AlterModelOptions(
            name='swipsvod',
            options={'managed': False, 'verbose_name': 'VOD 리스트', 'verbose_name_plural': 'VOD 리스트'},
        ),
    ]
