# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurryFixturesInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Match Id')),
                ('name', models.CharField(max_length=150)),
                ('startdate', models.DateTimeField()),
                ('league', models.PositiveIntegerField()),
                ('league_name', models.CharField(max_length=30)),
                ('broadcast_id', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_th', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_vn', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_br', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_kr', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_ph', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '중계정보입력',
                'verbose_name_plural': '중계정보입력',
                'db_table': 'curry_fixtures_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurryMajorFixtures',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Match Id')),
                ('league', models.CharField(max_length=30)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('status_type', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=1)),
                ('utc', models.CharField(max_length=12)),
                ('kst', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': '주요경기조회',
                'verbose_name_plural': '주요경기조회',
                'db_table': 'curry_major_fixtures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Match Id')),
                ('name', models.CharField(max_length=150)),
                ('tournament_stagefk', models.PositiveIntegerField(db_column='tournament_stageFK')),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('eventstatusfk', models.PositiveIntegerField(db_column='eventstatusFK')),
                ('status_type', models.CharField(max_length=11)),
                ('status_descfk', models.PositiveIntegerField(db_column='status_descFK')),
                ('enetid', models.IntegerField(db_column='enetID')),
                ('enetsportid', models.CharField(blank=True, db_column='enetSportID', max_length=2, null=True)),
                ('n', models.PositiveIntegerField()),
                ('ut', models.DateTimeField()),
                ('del_field', models.CharField(db_column='del', max_length=3)),
                ('locked', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': '경기',
                'verbose_name_plural': '경기',
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsFixturesInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('broadcast_id', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_th', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_vn', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_br', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_kr', models.CharField(blank=True, max_length=50, null=True)),
                ('broadcast_ph', models.CharField(blank=True, max_length=50, null=True)),
                ('ut', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '중계정보조회',
                'verbose_name_plural': '중계정보조회',
                'db_table': 'swips_fixtures_info',
                'managed': False,
            },
        ),
    ]
