# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_team_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curryplayer',
            options={'managed': False, 'verbose_name': '중복 선수 확인', 'verbose_name_plural': '중복 선수 확인'},
        ),
        migrations.AlterModelOptions(
            name='swipsleagueinfo',
            options={'managed': False, 'verbose_name': '리그', 'verbose_name_plural': '리그'},
        ),
        migrations.AlterModelOptions(
            name='swipsplayercareer',
            options={'managed': False, 'verbose_name': '선수 커리어', 'verbose_name_plural': '선수 커리어'},
        ),
        migrations.AlterModelOptions(
            name='swipsplayerinfo',
            options={'managed': False, 'verbose_name': '선수', 'verbose_name_plural': '선수'},
        ),
        migrations.AlterModelOptions(
            name='swipsteaminfo',
            options={'managed': False, 'verbose_name': '팀', 'verbose_name_plural': '팀'},
        ),
    ]
