# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipsTransfer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sport', models.IntegerField(help_text='1:football, 23: basketball, 26: baseball')),
                ('player_id', models.IntegerField(help_text='swips_player id, 찾을 수 없을떄에는 1로 기록')),
                ('player_name', models.CharField(blank=True, help_text='player_id를 찾을 수 없을때에만 영어로 기록', max_length=45, null=True)),
                ('position', models.CharField(blank=True, help_text='항상 2자의 영어대문자로 기록', max_length=10, null=True)),
                ('from_team_id', models.IntegerField(help_text='원 소속팀 id, 찾을 수 없을때에는 0으로 기록')),
                ('from_team_name', models.CharField(blank=True, help_text='from_team_id를 찾을 수 없을때에만 영어로 기록(첫자 대문자!)', max_length=45, null=True)),
                ('to_team_id', models.IntegerField(help_text='이적할 팀 id, 찾을 수 없을떄에는 0으로 기록')),
                ('to_team_name', models.CharField(blank=True, help_text='to_team_id를 찾을 수 없을떄에만 영어로 기록(첫자 대문자!)', max_length=45, null=True)),
                ('is_loan', models.IntegerField(help_text='0이면 이적, 1이면 임대')),
                ('type', models.CharField(choices=[('official', 'official'), ('agreed', 'agreed'), ('bid', 'bid'), ('rumor', 'rumor')], help_text='rumor:루머, bid:제안, agreed:확정, official:오피셜', max_length=10)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_th', models.CharField(blank=True, max_length=255, null=True)),
                ('source_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ko', models.CharField(blank=True, max_length=255, null=True)),
                ('source_vi', models.CharField(blank=True, max_length=255, null=True)),
                ('source_en', models.CharField(blank=True, max_length=255, null=True)),
                ('ut', models.DateTimeField()),
                ('contract_dt', models.DateField(help_text='신규계약 만료일')),
                ('contract_info', models.CharField(choices=[('confirm', 'confirm'), ('estimate', 'estimate'), ('close', 'close')], help_text='close:contract_dt가 보이지 않게함, estimate: 추정, confirm: 확정', max_length=8)),
                ('fee', models.BigIntegerField(help_text='이적금액 숫자로입력')),
                ('fee_info', models.CharField(choices=[('confirm', 'confirm'), ('estimate', 'estimate'), ('close', 'close')], help_text='close: fee가 보이지 않게함, estimate: 추정, confirm: 확정', max_length=8)),
                ('fee_currency', models.CharField(choices=[('euro', 'euro'), ('pound', 'pound'), ('dollar', 'dollar'), ('won', 'won')], help_text='통화', max_length=6)),
            ],
            options={
                'verbose_name': '이적',
                'verbose_name_plural': '이적',
                'db_table': 'swips_transfer',
                'managed': False,
            },
        ),
    ]
