# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurryAdBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('admob', 'admob'), ('mobvista', 'mobvista'), ('direct', 'direct')], help_text='직접광고는 direct', max_length=8)),
                ('weight', models.IntegerField(help_text='광고의 노출 빈도; admob/mobvista의 경우 0이어야함, direct일 경우는 0이 아니여야함')),
                ('country_cd', models.CharField(help_text='영문 대문자 2자리 입력', max_length=2)),
                ('os', models.CharField(help_text='"android" 또는 "ios"', max_length=7)),
                ('valid_until', models.CharField(help_text='광고가 끝나는 시점. UTC기준', max_length=12)),
                ('ut', models.DateTimeField(blank=True, null=True)),
                ('advertiser', models.CharField(blank=True, help_text='direct의 경우에만 입력. 임의의 입력', max_length=45, null=True)),
                ('link', models.CharField(blank=True, help_text='direct의 경우에만 입력. 연결될 링크', max_length=255, null=True)),
                ('image_link', models.CharField(blank=True, help_text='direct의 경우에만 입력. 이미지 주소', max_length=255, null=True)),
                ('ad_type', models.CharField(choices=[('native_m', 'native_m'), ('native_s', 'native_s'), ('banner', 'banner'), ('native_b', 'native_b')], help_text='"native_m" or "native_s" or "banner"', max_length=8)),
            ],
            options={
                'verbose_name': '광고 밸런스',
                'verbose_name_plural': '광고 밸런스',
                'db_table': 'curry_ad_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurryRdsScaleModifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(help_text='디비변경을 시작할 시간. 신규 생성은 20분가량, 삭제는 5분가량')),
                ('number', models.IntegerField(help_text='1~5사이의 숫자. 30분이내에 2번이상 변경을 시도하지말것')),
                ('description', models.CharField(blank=True, help_text='설명', max_length=255, null=True)),
                ('status', models.CharField(default='ready', max_length=9)),
                ('ut', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'RDS scale Modifier',
                'verbose_name_plural': 'RDS scale Modifier',
                'db_table': 'curry_rds_scale_modifier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsPush',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('push_type', models.IntegerField()),
                ('table_name', models.CharField(max_length=45)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=9)),
                ('delayed_until', models.DateTimeField(blank=True, null=True)),
                ('ref1', models.IntegerField(blank=True, null=True)),
                ('ref2', models.IntegerField(blank=True, null=True)),
                ('ref3', models.IntegerField(blank=True, null=True)),
                ('ref4', models.IntegerField(blank=True, null=True)),
                ('ref5', models.IntegerField(blank=True, null=True)),
                ('refstr1', models.CharField(blank=True, max_length=10, null=True)),
                ('refstr2', models.CharField(blank=True, max_length=2048, null=True)),
                ('refstr3', models.CharField(blank=True, max_length=255, null=True)),
                ('ut', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Swips Push',
                'verbose_name_plural': 'Swips Push',
                'db_table': 'swips_push',
                'managed': False,
            },
        ),
    ]
