# Generated by Django 2.0.4 on 2018-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steph_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurryNews',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('language_cd', models.CharField(blank=True, max_length=2, null=True)),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('create_tmp', models.DateTimeField(blank=True, null=True)),
                ('is_top', models.IntegerField()),
                ('sport', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('source', models.CharField(blank=True, max_length=45, null=True)),
                ('is_frifee_content', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('following_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('pushed', models.IntegerField()),
                ('del_field', models.IntegerField(blank=True, db_column='del', null=True)),
                ('pl_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('te_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('le_relation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'curry_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurryVod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('create_tmp', models.DateTimeField(blank=True, null=True)),
                ('is_top', models.IntegerField(blank=True, null=True)),
                ('sport', models.IntegerField(blank=True, null=True)),
                ('country_cd', models.CharField(blank=True, max_length=2, null=True)),
                ('language_cd', models.CharField(blank=True, max_length=2, null=True)),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('source', models.CharField(blank=True, max_length=45, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('following_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('is_frifee_content', models.IntegerField(blank=True, null=True)),
                ('pushed', models.IntegerField()),
                ('country_exclude_cd', models.CharField(blank=True, max_length=45, null=True)),
                ('del_field', models.IntegerField(blank=True, db_column='del', null=True)),
                ('is_live', models.IntegerField()),
                ('pl_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('te_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('le_relation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'vod',
                'verbose_name_plural': 'vod',
                'db_table': 'curry_vod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
    ]
