# Generated by Django 2.0.4 on 2018-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipsLineupCustom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField()),
                ('team', models.IntegerField()),
                ('lineup_number', models.IntegerField(blank=True, null=True)),
                ('shirt_number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=45)),
                ('ut', models.DateTimeField()),
            ],
            options={
                'db_table': 'swips_lineup_custom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsMatchDetailCustom',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('lineup_number', models.IntegerField(blank=True, null=True)),
                ('shirt_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=45)),
                ('type', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('ut', models.DateTimeField()),
            ],
            options={
                'db_table': 'swips_match_detail_custom',
                'managed': False,
            },
        ),
    ]
