# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('enetid', models.PositiveIntegerField(db_column='enetID')),
                ('n', models.PositiveIntegerField()),
                ('ut', models.DateTimeField()),
                ('del_field', models.CharField(db_column='del', max_length=3)),
                ('name_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name_th', models.CharField(blank=True, max_length=50, null=True)),
                ('name_vi', models.CharField(blank=True, max_length=50, null=True)),
                ('name_pt', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '국가',
                'verbose_name_plural': '국가',
                'db_table': 'country',
                'managed': False,
            },
        ),
    ]
