# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipsBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=2)),
                ('participant', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=2)),
                ('text', models.TextField(blank=True, null=True)),
                ('ut', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'swips_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsPoll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField()),
                ('number', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('participant', models.IntegerField(blank=True, null=True)),
                ('ut', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '투표',
                'verbose_name_plural': '투표',
                'db_table': 'swips_poll',
                'managed': False,
            },
        ),
    ]
