# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurryInfoDbModify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField()),
                ('type', models.CharField(max_length=2)),
                ('migrate_item', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('ut', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '앱 DB 변경',
                'verbose_name_plural': '앱 DB 변경',
                'db_table': 'curry_info_db_modify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurryInfoImageModify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField()),
                ('type', models.CharField(max_length=2)),
                ('desc', models.TextField(blank=True, null=True)),
                ('ut', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '이미지 변경',
                'verbose_name_plural': '이미지 변경',
                'db_table': 'curry_info_image_modify',
                'managed': False,
            },
        ),
    ]
