# Generated by Django 2.0.4 on 2018-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipsBoard',
            fields=[
                ('item', models.IntegerField(blank=True, null=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2)),
                ('participant', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=2)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Board',
                'db_table': 'swips_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsBoardLike',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2)),
                ('root_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('account_type', models.CharField(max_length=5)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'swips_board_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsBoardLikeDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('root_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('account_type', models.CharField(max_length=5)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'swips_board_like_dev',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsBoardPost',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2)),
                ('participant', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('account_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('like', models.IntegerField()),
                ('img_ext', models.CharField(blank=True, max_length=5, null=True)),
                ('img_rot', models.IntegerField(blank=True, null=True)),
                ('img_width', models.IntegerField(blank=True, null=True)),
                ('img_height', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField()),
                ('create_time', models.CharField(max_length=10)),
                ('edit_time', models.CharField(max_length=10)),
                ('top_time', models.CharField(max_length=10)),
                ('del_field', models.IntegerField(db_column='del')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
                'db_table': 'swips_board_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsBoardPostDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('participant', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('account_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('like', models.IntegerField()),
                ('img_ext', models.CharField(blank=True, max_length=5, null=True)),
                ('img_rot', models.IntegerField(blank=True, null=True)),
                ('img_width', models.IntegerField(blank=True, null=True)),
                ('img_height', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('edit_time', models.DateTimeField()),
                ('top_time', models.DateTimeField()),
                ('del_field', models.IntegerField(db_column='del')),
            ],
            options={
                'db_table': 'swips_board_post_dev',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsBoardReply',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2)),
                ('participant', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('root_type', models.IntegerField()),
                ('root_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('create_time', models.CharField(max_length=10)),
                ('edit_time', models.CharField(max_length=10)),
                ('del_field', models.IntegerField(db_column='del')),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'swips_board_reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwipsBoardReplyDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('participant', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('root_type', models.IntegerField()),
                ('root_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('edit_time', models.DateTimeField()),
                ('del_field', models.IntegerField(db_column='del')),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'swips_board_reply_dev',
                'managed': False,
            },
        ),
    ]
