# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swipsboardlike',
            options={'managed': False, 'verbose_name': '좋아요', 'verbose_name_plural': '좋아요'},
        ),
        migrations.AlterModelOptions(
            name='swipsboardpost',
            options={'managed': False, 'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AlterModelOptions(
            name='swipsboardreply',
            options={'managed': False, 'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
    ]
