# Generated by Django 2.0.4 on 2018-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurryExposePostLog',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=45)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('ut', models.DateTimeField()),
            ],
            options={
                'verbose_name': '작성글 Log',
                'verbose_name_plural': '작성글 Log',
                'db_table': 'curry_expose_post_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurryExposeTarget',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('ut', models.DateTimeField()),
            ],
            options={
                'verbose_name': '점령지 List',
                'verbose_name_plural': '점령지 List',
                'db_table': 'curry_expose_target',
                'managed': False,
            },
        ),
    ]
